package:
  name: shadow-utils-subid-conda-aarch64
  version: 4.9

source:
  - url: https://vault.almalinux.org/9.4/BaseOS/aarch64/os/Packages/shadow-utils-subid-4.9-8.el9.aarch64.rpm
    sha256: ff5ffe0329dc04689193d648c2f18f43f4538a57fa456fcd5c152e1e6ef89832
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/9.4/BaseOS/Source/Packages/shadow-utils-4.9-8.el9.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  skip: true  # [distro != "alma9"]

requirements:
  host:
    - sysroot_linux-aarch64 2.34.*
  run:
    - sysroot_linux-aarch64 2.34.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/shadow-maint/shadow
  license: BSD and GPLv2+
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: "(CDT) A library to manage subordinate uid and gid ranges"
  description: |
        Utility library that provides a way to manage subid ranges.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
