package:
  name: shadow-utils-subid-devel-conda-aarch64
  version: 4.9

source:
  - url: https://vault.almalinux.org/9.4/CRB/aarch64/os/Packages/shadow-utils-subid-devel-4.9-8.el9.aarch64.rpm
    sha256: 06015e0e7bc1845463d5dfe29d9e696950f26586fd9f1f946c4a4f4d48ececfa
    no_hoist: true
    folder: binary
  # - url: https://vault.almalinux.org/9.4/CRB/Source/Packages/shadow-utils-4.9-8.el9.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  skip: true  # [distro != "alma9"]

requirements:
  build:
    - shadow-utils-subid-conda-aarch64 ==4.9 *_{{ cdt_build_number|int + 1000 }}
  host:
    - shadow-utils-subid-conda-aarch64 ==4.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.34.*
  run:
    - shadow-utils-subid-conda-aarch64 ==4.9 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.34.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/shadow-maint/shadow
  license: BSD and GPLv2+
  license_family: GPL2
  summary: (CDT) Development package for shadow-utils-subid
  description: |
    Development files for shadow-utils-subid.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
